language: python
python:
    - '2.7'
sudo: false
cache:
    directories:
        - "~/.platformio"
install:
    - pip install -U platformio
script:
    - cd examples/advanced && pio run
    - cd examples/ap && pio run
    - cd examples/basic && pio run
    - cd examples/smartconfig && pio run
    - cd examples/wps && pio run
